# Parameters for compiling

ARDUINO_DIR     = %ARDUINO_DIR%
TARGET          = output
ARDUINO_LIBS    = %ARDUINO_LIBS%
MCU             = atmega168
F_CPU           = %CPU_FREQUENCY%


# Avrdude code for programming

# Programming is done straignt through Qt


# Arduino makefile

include $(ARDUINO_DIR)/Arduino.mk
