# Parameters for compiling

ARDUINO_DIR     = %ARDUINO_DIR%
TARGET          = output
ARDUINO_LIBS    = %ARDUINO_LIBS%


# Avrdude code for programming

BOARD_TAG               = %BOARD_TAG%
ARDUINO_PORT            = %ARDUINO_PORT%
AVRDUDE_ARD_PROGRAMMER  = arduino
AVRDUDE_ARD_BAUDRATE    = 115200

# Arduino makefile

include $(ARDUINO_DIR)/Arduino.mk

