# Parameters for compiling

ARDUINO_DIR     = %ARDUINO_DIR%
TARGET          = output
ARDUINO_LIBS    = %ARDUINO_LIBS%


# Avrdude code for programming

BOARD_TAG               = %BOARD_TAG%
ARDUINO_PORT            = %ARDUINO_PORT%
AVRDUDE_ARD_PROGRAMMER  = arduino
AVRDUDE_ARD_BAUDRATE    = 115200


# if you have placed the alternate core in your sketchbook directory, then you can just mention the core name alone. 
#ALTERNATE_CORE = attiny
# If not, you might have to include the full path.
#ALTERNATE_CORE_PATH = /home/sudar/Dropbox/code/arduino-sketches/hardware/attiny/

#BOARD_TAG = trinket5
#ISP_PROG = usbtiny
#MONITOR_PORT = /dev/ttyS0
#ARDUINO_LIBS = TrinketKeyboar

# Arduino makefile

include $(ARDUINO_DIR)/Arduino.mk

